# Generated by Django 2.2.15 on 2023-01-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20221226_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='degree',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Degree/Certificate Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='faculty',
            field=models.CharField(blank=True, choices=[(None, 'Select Faculty'), ('fac-1', 'ARTS'), ('fac-2', 'SCIENCE'), ('fac-3', 'ENGINEERING & TECHNOLOGY'), ('fac-4', 'ISLM')], max_length=100, null=True, verbose_name='Faculty :'),
        ),
        migrations.AlterField(
            model_name='priorpost',
            name='gross_salary',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Gross Salary (per annum)'),
        ),
        migrations.AlterField(
            model_name='research',
            name='institute',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Institute/ University'),
        ),
        migrations.AlterField(
            model_name='research',
            name='url_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Document(Certificate) link'),
        ),
    ]
