# Generated by Django 2.2.15 on 2023-04-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20230308_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='casformsts',
            name='academy_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='casformsts',
            name='api_catg1_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='casformsts',
            name='api_catg2_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='casformsts',
            name='e_learning_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='casformsts',
            name='fellow_award_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='casformsts',
            name='final_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='casformsts',
            name='general_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='casformsts',
            name='jrnl_pub_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='casformsts',
            name='jrnlpaper_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='casformsts',
            name='lecture_paper_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='casformsts',
            name='orientation_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='casformsts',
            name='present_post_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='casformsts',
            name='priorpost_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='casformsts',
            name='prj_outcm_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='casformsts',
            name='pub_other_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='casformsts',
            name='resch_cons_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='casformsts',
            name='resch_guide_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='casformsts',
            name='resch_proj_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='casformsts',
            name='research_paper_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='casformsts',
            name='teaching_no',
            field=models.IntegerField(default=0),
        ),
    ]
