# Generated by Django 2.2.15 on 2022-12-26 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catg_3', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jrnl_pub',
            name='jrnl_pdf',
        ),
        migrations.AddField(
            model_name='jrnl_pub',
            name='jrnl_link',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='Document Link'),
        ),
        migrations.AddField(
            model_name='jrnl_pub',
            name='jrnl_oth',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Other's number"),
        ),
        migrations.AddField(
            model_name='jrnl_pub',
            name='self_api_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Self Appraisal Score'),
        ),
        migrations.AddField(
            model_name='jrnl_pub',
            name='veri_api_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Verified API Score'),
        ),
        migrations.AlterField(
            model_name='jrnl_pub',
            name='imp_fac',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Impact Factor (put 0 if NA)'),
        ),
        migrations.AlterField(
            model_name='jrnl_pub',
            name='yr_pub',
            field=models.PositiveIntegerField(null=True, verbose_name='Year of Publication'),
        ),
        migrations.CreateModel(
            name='Resch_proj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_tag', models.CharField(blank=True, max_length=5, null=True, verbose_name='Proj tile')),
                ('faculty_app', models.CharField(blank=True, choices=[(None, 'Select'), ('ARTS', 'Arts'), ('SCNC', 'Science'), ('ENGG', 'Engineering & Technology')], max_length=50, null=True, verbose_name='Area of the Applicant')),
                ('proj_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title of the Project')),
                ('fund_agnc', models.CharField(blank=True, max_length=300, null=True, verbose_name='Funding Agency')),
                ('no_yrs', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (no.of years)')),
                ('prj_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Grant Sanctioned (in Lakhs)')),
                ('prj_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link of the Grant Letter')),
                ('prj_pdf', models.FileField(blank=True, null=True, upload_to='resch_proj/pdfs/', verbose_name='Upload Grant Letter(PDF)')),
                ('self_api_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Self Appraisal Score')),
                ('veri_api_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Verified API Score')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resch_guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Student Name')),
                ('degree', models.CharField(blank=True, choices=[(None, 'Select'), ('MPHIL', 'Mphil'), ('ME', 'ME'), ('MTECH', 'Mtech'), ('PHD', 'PhD')], max_length=20, null=True, verbose_name='Degree')),
                ('title_thesis', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title of the Thesis')),
                ('status', models.CharField(blank=True, choices=[(None, 'Select'), ('PHDR', 'Ph.D Registered'), ('DEGR', 'Degree awarded'), ('THES', 'Thesis submitted')], max_length=50, null=True, verbose_name='Status')),
                ('prj_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Upload document')),
                ('self_api_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Self Appraisal Score')),
                ('veri_api_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Verified API Score')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resch_cons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_tag', models.CharField(blank=True, max_length=5, null=True, verbose_name='Proj tile')),
                ('faculty_app', models.CharField(choices=[(None, 'Select'), ('ARTS', 'Arts'), ('SCNC', 'Science'), ('ENGG', 'Engineering & Technology')], error_messages={'blank': 'You must select an option!!!!! !', 'invalid': 'Wrong format.!!!!!'}, max_length=50, null=True, verbose_name='Area of the Applicant')),
                ('proj_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title of the Project')),
                ('fund_agnc', models.CharField(blank=True, max_length=300, null=True, verbose_name='Funding Agency')),
                ('no_yrs', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (no.of years)')),
                ('prj_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Amount Mobilized (Rs.in Lacs)')),
                ('prj_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link of the Grant Letter')),
                ('prj_pdf', models.FileField(blank=True, null=True, upload_to='resch_proj/pdfs/', verbose_name='Upload Grant Letter(PDF)')),
                ('self_api_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Self Appraisal Score')),
                ('veri_api_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Verified API Score')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pub_other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yr_pub', models.PositiveIntegerField(blank=True, null=True, verbose_name='Year of Publication')),
                ('pub_type', models.CharField(blank=True, choices=[(None, 'Select'), ('TEXT_BK', 'Text Book'), ('REF_BK', 'Reference Book'), ('BK_CHAP', 'Book Chapter')], max_length=50, null=True, verbose_name='Type of Publication')),
                ('chap_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title of the Chapter')),
                ('bk_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title of the Book')),
                ('no_auth', models.PositiveIntegerField(blank=True, null=True, verbose_name='No.of Authors')),
                ('name_pub', models.CharField(blank=True, max_length=300, null=True, verbose_name='Name of the Publisher')),
                ('sts_pub', models.CharField(blank=True, choices=[(None, 'Select'), ('INTL', 'International'), ('NATL', 'National'), ('LOCL', 'Local')], max_length=50, null=True, verbose_name='Status of Publisher')),
                ('isbn_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='ISBN/ISSN No.')),
                ('pub_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link of the Publication/Book/Book chapter')),
                ('pub_pdf', models.FileField(blank=True, null=True, upload_to='pub_other/pdfs/', verbose_name='Upload Paper(PDF)')),
                ('self_api_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Self Appraisal Score')),
                ('veri_api_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Verified API Score')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prj_outcm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_app', models.CharField(blank=True, choices=[(None, 'Select'), ('ARTS', 'Arts'), ('SCNC', 'Science'), ('ENGG', 'Engineering & Technology')], max_length=50, null=True, verbose_name='Area of the Applicant')),
                ('prj_type', models.CharField(blank=True, choices=[(None, 'Select'), ('MPD', 'Major Policy Document'), ('PTNT', 'Patent'), ('TETR', 'Technology Transfer'), ('PRDT', 'Product'), ('PRCS', 'Process')], max_length=50, null=True, verbose_name='Type of Project')),
                ('proj_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title of the Project')),
                ('prj_lvl', models.CharField(blank=True, choices=[(None, 'Select'), ('INTR', 'International'), ('NATL', 'National'), ('LCL', 'Local'), ('CNGV', 'National (Central Govt.)'), ('STGV', 'State Govt.')], max_length=50, null=True, verbose_name='Level')),
                ('ref_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Document No./Patent No/Other reference no')),
                ('ptnt_sts', models.CharField(blank=True, choices=[(None, 'Select'), ('FILE', 'Filed'), ('PUBG', 'Published'), ('GRNT', 'Granted')], max_length=50, null=True, verbose_name='Patent Status')),
                ('prj_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link of Document')),
                ('prj_pdf', models.FileField(blank=True, null=True, upload_to='resch_proj/pdfs/', verbose_name='Upload Grant Letter(PDF)')),
                ('self_api_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Self Appraisal Score')),
                ('veri_api_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Verified API Score')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture_Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_type', models.CharField(blank=True, choices=[(None, 'Select'), ('LECT', 'Invited Lecture'), ('PAPER', 'Paper presented')], max_length=50, null=True, verbose_name='Invitation Type')),
                ('title_lecture', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title of the Lecture / Paper')),
                ('seminer', models.CharField(blank=True, max_length=300, null=True, verbose_name='Name of the Conference/Seminar/ Workshop')),
                ('organizer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Organized by')),
                ('venue', models.CharField(blank=True, max_length=300, null=True, verbose_name='Venue')),
                ('duration', models.CharField(blank=True, max_length=200, null=True, verbose_name='Duration')),
                ('prj_lvl', models.CharField(blank=True, choices=[(None, 'Select'), ('INTR', 'International'), ('NATL', 'National'), ('LCL', 'State'), ('UNIV', 'University')], max_length=50, null=True, verbose_name='Level')),
                ('prj_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Upload document')),
                ('self_api_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Self Appraisal Score')),
                ('veri_api_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Verified API Score')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JrnlPaper_UGC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jrnl_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Journal Name')),
                ('paper_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title of the paper')),
                ('yr_review', models.PositiveIntegerField(blank=True, null=True, verbose_name='Year of review submission')),
                ('ltr_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Review Invitation Letter Link')),
                ('sub_ltr_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Review submission document link')),
                ('self_api_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Self Appraisal Score')),
                ('veri_api_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Verified API Score')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fellow_Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fellow_type', models.CharField(blank=True, choices=[(None, 'Select'), ('FELLOW', 'Fellowship'), ('AWARD', 'Award for academic bodies/ Association')], max_length=50, null=True, verbose_name='Fellow Type')),
                ('name_fellow', models.CharField(blank=True, max_length=300, null=True, verbose_name='Name of the Fellowship/Award')),
                ('name_body', models.CharField(blank=True, max_length=300, null=True, verbose_name='Name of the Fellowship/Award')),
                ('prj_lvl', models.CharField(blank=True, choices=[(None, 'Select'), ('INTR', 'International'), ('NATL', 'National'), ('LCL', 'State'), ('UNIV', 'University')], max_length=50, null=True, verbose_name='Level')),
                ('prj_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Upload document')),
                ('self_api_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Self Appraisal Score')),
                ('veri_api_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Verified API Score')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='E_Learning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name of the model')),
                ('course_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name of the courses')),
                ('program_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='NAme of the programs')),
                ('prj_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Upload document')),
                ('self_api_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Self Appraisal Score')),
                ('veri_api_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Verified API Score')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
