# Generated by Django 2.2.15 on 2023-04-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catg_3', '0005_auto_20230320_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jrnl_pub',
            name='role_appl',
            field=models.CharField(blank=True, choices=[(None, 'Select'), ('F_A', 'First author'), ('C_A', 'Corresponding author / supervisor / mentor'), ('FC_A', 'First and Corresponding author'), ('O_A', 'Other co-author')], max_length=50, null=True, verbose_name='Role of Applicant'),
        ),
        migrations.AlterField(
            model_name='pub_other',
            name='pub_type',
            field=models.CharField(blank=True, choices=[(None, 'Select'), ('TEXT_BK', 'Text Book'), ('REF_BK', 'Reference Book'), ('BK_CHAP', 'Book Chapter/ Conf. Proceedings')], max_length=50, null=True, verbose_name='Type of Publication'),
        ),
    ]
