# Generated by Django 4.2.1 on 2023-05-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catg_3', '0006_auto_20230418_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resch_guide',
            name='degree',
            field=models.CharField(blank=True, choices=[(None, 'Select'), ('MPHIL', 'Mphil'), ('ME', 'ME'), ('MTECH', 'Mtech'), ('MPHARM', 'MPHARM'), ('PHD', 'PhD')], max_length=20, null=True, verbose_name='Degree'),
        ),
    ]
